### ISSUE TITLE
CALLSP/CALLBG/CALL aren't highlighted.

### ISSUE THREAD

**Issue by ansxor** [PatheticFish/smilebasic-mode#2]
Pretty self-explanatory title.
[Picture of CALL in use but not highlighted.](https://i.imgur.com/wpwKUFX.png)

**Comment by y-ack** [comment]
Yet another issue of font-lock regexp differing slightly from other expectations of valid regex in Emacs, I think.  I fiddled with it a bit but couldn't stumble on the easy answer so I'll have to look at it more later.
To be fair, SmileBASIC'S parser has to handle CALL (SPRITE|BG) specially too.

**Comment by y-ack** [comment]
resolved in https://github.com/PatheticFish/smilebasic-mode/commit/d3b20c92051e3cfae5137d1e4ce2ba8126494794
